name: toku_learning_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  lottie: ^3.3.1
  animated_bottom_navigation_bar: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/numbers/
    - assets/images/familyMembers/
    - assets/images/colorsimage/ 
    - assets/sounds/family_Members/
    - assets/sounds/numberssound/
    - assets/sounds/colors/
    - assets/sounds/phrases/
    - assets/images/background/
    - assets/images/splash/
    - assets/animation/


